---
name: build_archstats

on:
  workflow_call:
    inputs:
      goos:
        required: true
        type: string
      goarch:
        required: true
        type: string
      package-name:
        type: string
        default: archstats
      bin-name:
        type: string
        default: archstats
      version:
        type: string
        required: true
      runson:
        type: string
        required: true
      release:
        type: string
        required: true

jobs:
  build:
    runs-on: ${{ inputs.runson }}
    name: ${{ inputs.goos }} ${{ inputs.goarch }} ${{ inputs.version }}
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-go@v4.0.1
        with:
          go-version: 1.21

      - if: ${{inputs.goos != 'darwin' }}
        run: |-
          sudo apt-get install gcc-multilib

      - if: ${{inputs.goos == 'windows' }}
        run: |-
          sudo apt-get install gcc-mingw-w64

      - if: ${{inputs.goos == 'windows' && inputs.goarch == 'amd64'}}
        run: |-
          echo "CC=x86_64-w64-mingw32-gcc" >> $GITHUB_ENV

      - if: ${{inputs.goos == 'windows' && inputs.goarch == '386'}}
        run: |-
          echo "CC=i686-w64-mingw32-gcc" >> $GITHUB_ENV

      - if: ${{inputs.goos == 'linux' && inputs.goarch == 'arm64'}}
        run: |-
          sudo apt-get install gcc-aarch64-linux-gnu
          echo "CC=aarch64-linux-gnu-gcc" >> $GITHUB_ENV

      - if: ${{inputs.goos == 'linux' && inputs.goarch == '386'}}
        run: |-
          echo "CC=gcc" >> $GITHUB_ENV


      - name: Determine artifact basename
        run: echo "ARTIFACT_BASENAME=${{ inputs.package-name }}-${{inputs.version}}-${{ inputs.goos }}_${{ inputs.goarch }}.tar.gz" >> $GITHUB_ENV
      - name: Build Archstats
        env:
          GOOS: ${{ inputs.goos }}
          GOARCH: ${{ inputs.goarch }}
          ACTIONSOS: ${{ inputs.runson }}
          CC: ${{ env.CC }}
          CGO_ENABLED: 1
        run: |-
          mkdir dist out
          set -x
          go build -o dist/ .
          tar -czvf out/${{ env.ARTIFACT_BASENAME }} dist/${{ inputs.bin-name }}
          md5sum out/${{ env.ARTIFACT_BASENAME }} > out/${{ env.ARTIFACT_BASENAME }}.md5
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ env.ARTIFACT_BASENAME }}
          path: out/${{ env.ARTIFACT_BASENAME }}
          if-no-files-found: error
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ env.ARTIFACT_BASENAME }}.md5
          path: out/${{ env.ARTIFACT_BASENAME }}.md5
          if-no-files-found: error
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          gh release upload ${{ inputs.version }} out/${{ env.ARTIFACT_BASENAME }} --repo archstats/archstats --clobber
          gh release upload ${{ inputs.version }} out/${{ env.ARTIFACT_BASENAME }}.md5 --repo archstats/archstats --clobber
          
        

