name: Release Archstats
on:
  release:
    types: [published]

permissions:
    contents: write
    packages: write

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

  releases:
    uses: ./.github/workflows/build.yml
    needs:
      - get-version
    strategy:
      fail-fast: false
      matrix:
       include:
         - { goos: "linux", goarch: "386", runson: "ubuntu-latest"}
         - { goos: "linux", goarch: "amd64", runson: "ubuntu-latest"}
         - { goos: "linux", goarch: "arm64", runson: "ubuntu-latest"}
         - { goos: "windows", goarch: "386", runson: "ubuntu-latest"}
         - { goos: "windows", goarch: "amd64", runson: "ubuntu-latest"}
         - { goos: "darwin", goarch: "amd64", runson: "macos-latest"}
         - { goos: "darwin", goarch: "arm64", runson: "macos-latest" }
    with:
      goarch: ${{ matrix.goarch }}
      goos: ${{ matrix.goos }}
      package-name: archstats
      product-version: ${{ env.RELEASE_VERSION }}
      runson: ${{ matrix.runson }}
